[build]
publish = "public"
command = "node getGithubData && npm run build"

[[plugins]]
package = "netlify-plugin-cecil-cache"

  [plugins.inputs]
  cacheDir = ".cache"
  debug = true

[[redirects]]
from = "/repos/:pageNr(\\d+)/:searchTerms?"
to = "/.netlify/functions/serverless"
status = 200
force = true
_generated_by_eleventy_serverless = "serverless"
